config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end 

app/models/category.rb
class Category < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save {self.email = email.downcase }
  validates :username, presence: true, 
            uniqueness: {case_sensitive: false},
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[-\w.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive: false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  helper_method :current_user, :logged_in?
  

  
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = " Debes estar logeado para esta accion"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index 
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    
  end
  
  def create
    
    @article = Article.new(article_params)
    @article.user = current_user
    
    if @article.save
      flash[:success] = "Articulo creado exitosamente"
      redirect_to article_path(@article)
    else 
      render 'new'
    end
  end
  
  def update 
    if @article.update(article_params)
      flash[:success] = "Articulo actualizado exitosamente"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def destroy
    
    @article = Article.find(params[:id])
    
    @article.destroy
    
    flash[:danger] = "Articulo borrado exitosamente"
    
    redirect_to articles_path
  end
  
  private
  
    def set_article
      @article = Article.find(params[:id])
    end
    
    def article_params
    params.require(:article).permit(:title, :description)
    end
    
    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "Tu solo puedes editar o borrar tus propios articulos"
        redirect_to root_path
      end
    end
    
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
  def about

  end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Has ingresado exitosamente"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Algo fue mal con tu informacion de acceso"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "Te has salido de la sesion"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update] 
  before_action :require_admin, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Bienvenido a Aduanas #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
    
  end


  def update
    if @user.update(user_params)
    flash[:success] = "Tu cuenta fue actualizada con exito"
    redirect_to articles_path
    else
    render 'edit'
    end
  end
  
  
  def show 
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end 
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "Este usuario y todos sus articulos creados han sido borrados"
    redirect_to users_path
  end
  

private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end


  def set_user
    @user = User.find (params[:id])
  end
  
  def require_same_user
    if current_user != @user
      flash[:danger] = "Solo puedes editar tu propia cuenta" 
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Solo el administrador puede hacer esto"
      redirect_to root_path
    end
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class:"img-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

    <div class="row">

      <div class="col-xs-8 col-xs-offset-2">

        <div class="well well-lg">

          <div class="article-title">

            <%= link_to article.title, article_path(article) %>

          </div>

          <div class="article-body">

            <%= truncate(article.description, length: 100) %>
            <div class="article-meta-details">
              <small> Creado por: <%= article.user.username if article.user%>,
                              hace <%= time_ago_in_words(article.created_at) %>,
                              Ultima actualizacion hace: <%= time_ago_in_words(article.updated_at) %> </small>
            </div>
          </div>
          
          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <div class="article-actions">
  
              <%= link_to "Editar esta pregunta", edit_article_path(article), class: "btn btn-xs btn-primary" %>
  
              <%= link_to "Borrar esta pregunta", article_path(article), 
              
                                                method: :delete,
  
                                                data: { confirm: "¿Seguro que quieres borrarlo?"},
  
                                                class: "btn btn-xs btn-danger" %>
  
            </div>
          <% end %>

        </div>

      </div>

    </div>

<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='row'>
  <div class='col-xs-12'>
    
    <%= form_for(@article, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Escribir regunta", autofocus: true %>
        </div>  
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 1000,  class: "form-control", placeholder: "Escribir espuesta" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn-primary btn-lg' %>
        </div>
      </div>
      
    <% end %>
    
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancelar y volver a la lista de preguntas", articles_path %> ]
    </div>
    
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editar articulo</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Lista de preguntas</h1>
<div align="center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center"> Crear nueva pregunta</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Titulo: <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
      <ul class="listing">
        <div class="row center">
          <div class="col-md-4 col-md-offset-4">
            <li>Created by: </li>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li class="article-title">
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
            <li><small>
              <%= pluralize(@article.user.articles.count, "pregunta") if @article.user.articles %>
              </small></li>
          </div>
        </div>
      </ul>
    <% end %>
  <h4 class="center description"><strong>Respuesta:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Editar esta pregunta", edit_article_path(@article), class: "btn btn-xs btn-primary" %>  
      <%= link_to "Borrar esta pregunta", article_path(@article), method: :delete, 
                                        data: { confirm: "¿Estas seguro de borrar este articulo?"},
                                        class: "btn btn-xs btn-danger" %>  
    <% end %>
    <%= link_to "Ver todas las preguntas", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://www.xiaomiuniverse.com"> Xiaomi Universe</a>
      by <a href= "https://www.linkedin.com/in/nicolascorbalan/">Nicolas Corbalan</a>
    </small>
    <nav>
      <ul>
        <li><%=link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Navegacion</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Aduanas Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articulos", articles_path %></li>
        <li><%= link_to "Usuarios", users_path %></li>
        <% if logged_in? %>  
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Acciones <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Nuevo articulo", new_article_path %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Categoria</a></li>
            </ul>
          </li>
          <% end %>
          
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Salir', logout_path, method: :delete %></li>
          <li class="Menu">
            #<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Perfil <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Editar tu perfil", edit_user_path(current_user) %></li>
              <li><%= link_to "Ver tu perfil", user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Categoria</a></li>
            </ul>
          </li>
          
          <% else %>
            <li><%= link_to 'Entrar', login_path %></li>
            <li><%= link_to 'Registrarte', signup_path %></li>
          <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aduanas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Esta es la pagina sobre mi en Aduanas</h1>

<%= link_to 'Ir a la pagina principal', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Aduanas</h1>
  <%= link_to "Registrarse", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
             que hacen que el articulo no se guarde:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
  <div class='col-xs-12'>
    
    <%= form_for(@user, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class: "form-control", placeholder: "Escribe usuario", autofocus: true %>
        </div>  
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">
          <%= f.email_field :email, class: "form-control", placeholder: "Escribir email" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Escribir password" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ?  "Registrar" : "Actualizar cuenta", class: 'btn-primary btn-lg') %>
        </div>
      </div>
      
    <% end %>
    
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancelar y volver a la lista de preguntas", articles_path %> ]
    </div>
    
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Editar tu cuenta</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Aduanas blog</h1>
<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
            <% if logged_in? and current_user.admin? %>
              <li><%= link_to "Borrar este usuario", user_path(user), method: :delete, 
                    data: {confirm: "¿estas seguro de eliminar este usuario y todos sus articulos?"} %></li>
          <% end %>
        </div>
      </div>
     </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Registrate en Aduanas</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Bienvenido a <%= @user.username %>´s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center"><%=@user.username %>´s articles</h4>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>